---
book_repo: pivotal-cf/docs-book-telmetry
layout_repo: pivotal-cf/docs-layout-repo
layout_repo_ref: 'master'

broken_link_exclusions: iefix|arrowhead
repo_link_enabled: true

elastic_search: true

public_host: docs.pivotal.io

feedback_enabled: true

sections:
- repository:
    name: pivotal-cf/docs-telemetry
    ref: 'master'
  directory: telemetry
  subnav_template: telemetry.erb
  product_info:
    use_local_header: true
    latest_stable_version:
    local_header_img: /images/cloud_rings.png
    local_header_title: Telemetry Collector for PCF
    search_placeholder: Search Telemetry Collector
    url_prefix: telemetry
    local_product_version: 1.0
    local_header_links: []
    local_header_version_list:
      
